controller:
  hero_chassis_controller:
    type: hero_chassis_controller/HeroChassisController

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

wheel_track: 0.4
wheal_base: 0.4
heel_radius: 0.07625
#这些参数从URDF中获取